HMS/Areas/Dashboard/Controllers/AccomodationTypesController.cs
using HMS.Areas.Dashboard.ViewModels;
using HMS.Entities;
using HMS.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMS.Areas.Dashboard.Controllers
{
    public class AccomodationTypesController : Controller
    {
        AccomodationTypesService accomodationTypesService = new AccomodationTypesService();
        // GET: Dashboard/AccomodationTypes
        public ActionResult Index()
        {
            return View();
        }
       
        public ActionResult Listing()
        {
            AccomodationTypesListingModel model = new AccomodationTypesListingModel();
            model.AccomodationTypes = accomodationTypesService.getAllAccomodationTypes();


            return PartialView("_Listing",model);
        }
        [HttpGet]
        public ActionResult Action()
        {
            AccomodationTypesActionModel model = new AccomodationTypesActionModel(); 
            return PartialView("_Action",model);
        }
        [HttpPost]
        public JsonResult Action(AccomodationTypesActionModel model)
        {
            JsonResult json = new JsonResult();
            AccomodationType accomodationType = new AccomodationType();
            accomodationType.Name = model.Name;
            accomodationType.Description = model.Description;
           var result= accomodationTypesService.SaveAccomodationType(accomodationType);
            if(result)
            {
                json.Data = new { Success = true };

            }
            else
            {
                json.Data = new { Success = true,message="Unable to add AccomodationType" };
            }
            return json;
        }
    }
}

HMS/Areas/Dashboard/Views/AccomodationTypes/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col col-lg-12">
        <h2>AccomodationTypes</h2>
        <hr />
    </div>

</div>

<div class="row mb-3">
    <div class="col col-lg-12">
        <div class="row">
    <div class="col col-lg-12">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" aria-label="Recipient's username with two button addons" aria-describedby="button-addon4">
            <div class="input-group-append" id="button-addon4">
                <button class="btn btn-outline-primary" type="button">Search</button>
                <button class="btn btn-outline-secondary" type="button">Reset</button>
                <button id="createButton" class="btn btn-outline-success" type="button" data-toggle="modal" data-target="#actionModal">Create</button>

            </div>
        </div>
        
    </div>

</div>
    </div>

</div>

<div class="row">
    <div class="col col-lg-12">
        @{ Html.RenderAction("Listing");
        }
        
    </div>

</div>

<div class="modal fade" id="actionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
       
    </div>
</div>
<script>
    $("#createButton").click(function () {
        $.ajax({
            url: '@Url.Action("Action","AccomodationTypes")',

        })
            .done(function (response) {
                $("#actionModal .modal-dialog").html(response);
            });
    });
</script>

HMS/Areas/Dashboard/Views/AccomodationTypes/_Action.cshtml
@model HMS.Areas.Dashboard.ViewModels.AccomodationTypesActionModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Create</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <div class="form-group">
                    <label >Name</label>
                    <input type="text" class="form-control" name="Name"  placeholder="Enter Accomodation type Name">
                   
                </div>
                <div class="form-group">
                    <label >Description</label>
                    <textarea class="form-control" name="Description" placeholder="Enter Accomodation type description ">

</textarea>
                </div>
               
               
            </form>
            <div class="errorDiv">

            </div>

        </div>
        <div class="modal-footer">
            <button  type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button id="actionButton" type="button" class="btn btn-primary">Save changes</button>
        </div>
    </div>


}
<script>
    $("#actionButton").click(function () {
        $.ajax({
            url: '@Url.Action("Action","AccomodationTypes")',
            type: "post",
            data: $("#actionForm").serialize()
        })
            .done(function (response) {
                if (response.Success) {
                    location.reload();
                }
                else {
                    $(".errorDiv").html(response.Message)
                }
            });
    });
</script>

HMS/Areas/Dashboard/Views/AccomodationTypes/_Listing.cshtml
@model HMS.Areas.Dashboard.ViewModels.AccomodationTypesListingModel

@if (Model != null && Model.AccomodationTypes != null && Model.AccomodationTypes.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>

                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var accomodationType in Model.AccomodationTypes)
            {
                <tr>

                    <td>@accomodationType.Name</td>
                    <td>@accomodationType.Description</td>
                    <td>
                        <button type="button" class="btn btn-success">Edit</button>
                        <button type="button" class="btn btn-danger">Delete</button>
                    </td>
                </tr>
            }
            @*<tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>@fat</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>Larry</td>
                    <td>the Bird</td>
                    <td>@twitter</td>
                </tr>*@
        </tbody>
    </table>

}
else
{
    <div class="alert alert-warning" role="alert">
        Sorry! No records exist.
    </div>
}